import { useTheme } from "next-themes";
import styles from "../styles/index.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Renish.is</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <nav>
        <div className={styles.imageContainer}>
          <Image
            src="/logo.svg"
            alt="Logo"
            objectFit="contain"
            width={0}
            height={0}
            className={styles.logoImage}
          />
        </div>
      </nav>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
        <text
          onClick={() => {
            theme == "dark" ? setTheme("light") : setTheme("dark");
          }}
        >
          Switch color
        </text>
      </main>
    </>
  );
}
